### ISSUE TITLE
Добавить поле Я согласен (-на) на обработку

### ISSUE THREAD

**Issue by Sashamailrias** [MalahVitalij/rocket-avrial#71]
Добавить всем формам Я согласен (-на) на обработку моих данных (по примеру формы Заказать расчет)

**Comment by Sashamailrias** [comment]
сделать текст "Я согласен (-на)" http://prntscr.com/l4rr78 ссылкой на политику конфиденциальности

**Comment by VladyslavKovalchuk** [comment]
добавить выделение чекбокса красным, если он не заполнен после отправки

**Comment by VladyslavKovalchuk** [comment]
добавить еще в формы "записаться на осмотр", "заказать услугу" и "отправить заявку"

**Comment by SeregaWeb** [comment]
15минут
