### ISSUE TITLE
Форма Заказать расчет

### ISSUE THREAD

**Issue by Sashamailrias** [MalahVitalij/rocket-avrial#79]
Обрезаются поля http://prntscr.com/l41nj4
В поле мейл нет проверки на мейл

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/l57hon постоянно ругается на почту

**Comment by VladyslavKovalchuk** [comment]
на почту уже не ругается, нормально валидирует, но не работает капча http://kyhni-trevi.rocketcompany.website/siteOne/
